import {defineApp,feature} from './domain-config.mjs';
export default defineApp({
  "id": "ai-clinical-research-medicare-coverage-billing-compliance",
  "engine": "recovery",
  "title": "Clinical Research Medicare Coverage & Billing Compliance",
  "shortTitle": "Clinical Research Medicare Coverage and Billing Compliance",
  "tagline": "Prevent double billing while ensuring routine-care services and sponsor obligations are billed to the correct responsible party.",
  "industry": "Clinical Research Finance",
  "buyer": "Academic medical centers and research sites",
  "uiPort": 4655,
  "apiPort": 5655,
  "accent": "#be123c",
  "currency": "USD",
  "primaryOutcome": "Clinical Research Medicare Coverage & Billing Compliance converted into governed, evidence-backed financial outcomes",
  "valueNarrative": "Connect protocols, coverage analyses, budgets, informed consent, enrollment, orders, services, modifiers, claims, sponsor invoices, and payments in one accountable workflow. Prevent double billing while ensuring routine-care services and sponsor obligations are billed to the correct responsible party.",
  "calculation": {
    "actualKey": "chargedAmount",
    "expectedKey": "supportedAmount",
    "actualLabel": "Charged or Paid Amount",
    "expectedLabel": "Evidence-Supported Amount",
    "varianceLabel": "Potential recovery or avoided cost",
    "direction": "actual-minus-expected",
    "finding": "Clinical Research Medicare Coverage & Billing Compliance evidence indicates a measurable financial exception.",
    "actions": [
      "Validate the effective agreement, eligibility rules, and accountable parties",
      "Reconcile transaction-level operational and financial evidence",
      "Prepare the correction, recovery, or compliance package",
      "Track counterparty response, approval, cash, and preventive control closure"
    ]
  }
},[
feature("study-protocol-registry","CRM01","Study protocol registry","Execute study protocol registry using protocols, coverage analyses, budgets, informed consent, enrollment, orders, services, modifiers, claims, sponsor invoices, and payments.","Produce a governed study protocol registry decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Study / Participant Encounter","text","Study / Participant Encounter · Standard Case"],["caseReference","Study protocol registry Reference","text","CRM01-2026-001"],["chargedAmount","Charged or Paid Amount","currency",672500],["supportedAmount","Evidence-Supported Amount","currency",564900],["domainDriver","Payer Responsibility","select","Routine cost",["Routine cost","Sponsor paid","Non-billable research"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"chargedAmount",subjects:["Study protocol registry case","Coverage analysis case","National coverage rule mapping case","Sponsor budget mapping case","Participant enrollment case"]}),
feature("coverage-analysis","CRM02","Coverage analysis","Execute coverage analysis using protocols, coverage analyses, budgets, informed consent, enrollment, orders, services, modifiers, claims, sponsor invoices, and payments.","Produce a governed coverage analysis decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Study / Participant Encounter","text","Study / Participant Encounter · Standard Case"],["caseReference","Coverage analysis Reference","text","CRM02-2026-001"],["chargedAmount","Charged or Paid Amount","currency",672500],["supportedAmount","Evidence-Supported Amount","currency",564900],["domainDriver","Payer Responsibility","select","Routine cost",["Routine cost","Sponsor paid","Non-billable research"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"chargedAmount",subjects:["Study protocol registry case","Coverage analysis case","National coverage rule mapping case","Sponsor budget mapping case","Participant enrollment case"]}),
feature("national-coverage-rule-mapping","CRM03","National coverage rule mapping","Execute national coverage rule mapping using protocols, coverage analyses, budgets, informed consent, enrollment, orders, services, modifiers, claims, sponsor invoices, and payments.","Produce a governed national coverage rule mapping decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Study / Participant Encounter","text","Study / Participant Encounter · Standard Case"],["caseReference","National coverage rule mapping Reference","text","CRM03-2026-001"],["chargedAmount","Charged or Paid Amount","currency",672500],["supportedAmount","Evidence-Supported Amount","currency",564900],["domainDriver","Payer Responsibility","select","Routine cost",["Routine cost","Sponsor paid","Non-billable research"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"chargedAmount",subjects:["Study protocol registry case","Coverage analysis case","National coverage rule mapping case","Sponsor budget mapping case","Participant enrollment case"]}),
feature("sponsor-budget-mapping","CRM04","Sponsor budget mapping","Execute sponsor budget mapping using protocols, coverage analyses, budgets, informed consent, enrollment, orders, services, modifiers, claims, sponsor invoices, and payments.","Produce a governed sponsor budget mapping decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Study / Participant Encounter","text","Study / Participant Encounter · Standard Case"],["caseReference","Sponsor budget mapping Reference","text","CRM04-2026-001"],["chargedAmount","Charged or Paid Amount","currency",672500],["supportedAmount","Evidence-Supported Amount","currency",564900],["domainDriver","Payer Responsibility","select","Routine cost",["Routine cost","Sponsor paid","Non-billable research"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"chargedAmount",subjects:["Study protocol registry case","Coverage analysis case","National coverage rule mapping case","Sponsor budget mapping case","Participant enrollment case"]}),
feature("participant-enrollment","CRM05","Participant enrollment","Execute participant enrollment using protocols, coverage analyses, budgets, informed consent, enrollment, orders, services, modifiers, claims, sponsor invoices, and payments.","Produce a governed participant enrollment decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Study / Participant Encounter","text","Study / Participant Encounter · Standard Case"],["caseReference","Participant enrollment Reference","text","CRM05-2026-001"],["chargedAmount","Charged or Paid Amount","currency",672500],["supportedAmount","Evidence-Supported Amount","currency",564900],["domainDriver","Payer Responsibility","select","Routine cost",["Routine cost","Sponsor paid","Non-billable research"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"chargedAmount",subjects:["Study protocol registry case","Coverage analysis case","National coverage rule mapping case","Sponsor budget mapping case","Participant enrollment case"]}),
feature("encounter-order-linking","CRM06","Encounter order linking","Execute encounter order linking using protocols, coverage analyses, budgets, informed consent, enrollment, orders, services, modifiers, claims, sponsor invoices, and payments.","Produce a governed encounter order linking decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Study / Participant Encounter","text","Study / Participant Encounter · Standard Case"],["caseReference","Encounter order linking Reference","text","CRM06-2026-001"],["chargedAmount","Charged or Paid Amount","currency",672500],["supportedAmount","Evidence-Supported Amount","currency",564900],["domainDriver","Payer Responsibility","select","Routine cost",["Routine cost","Sponsor paid","Non-billable research"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"chargedAmount",subjects:["Study protocol registry case","Coverage analysis case","National coverage rule mapping case","Sponsor budget mapping case","Participant enrollment case"]}),
feature("routine-cost-determination","CRM07","Routine cost determination","Execute routine cost determination using protocols, coverage analyses, budgets, informed consent, enrollment, orders, services, modifiers, claims, sponsor invoices, and payments.","Produce a governed routine cost determination decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Study / Participant Encounter","text","Study / Participant Encounter · Standard Case"],["caseReference","Routine cost determination Reference","text","CRM07-2026-001"],["chargedAmount","Charged or Paid Amount","currency",672500],["supportedAmount","Evidence-Supported Amount","currency",564900],["domainDriver","Payer Responsibility","select","Routine cost",["Routine cost","Sponsor paid","Non-billable research"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"chargedAmount",subjects:["Study protocol registry case","Coverage analysis case","National coverage rule mapping case","Sponsor budget mapping case","Participant enrollment case"]}),
feature("sponsor-paid-service-detection","CRM08","Sponsor-paid service detection","Execute sponsor-paid service detection using protocols, coverage analyses, budgets, informed consent, enrollment, orders, services, modifiers, claims, sponsor invoices, and payments.","Produce a governed sponsor-paid service detection decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Study / Participant Encounter","text","Study / Participant Encounter · Standard Case"],["caseReference","Sponsor-paid service detection Reference","text","CRM08-2026-001"],["chargedAmount","Charged or Paid Amount","currency",672500],["supportedAmount","Evidence-Supported Amount","currency",564900],["domainDriver","Payer Responsibility","select","Routine cost",["Routine cost","Sponsor paid","Non-billable research"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"chargedAmount",subjects:["Study protocol registry case","Coverage analysis case","National coverage rule mapping case","Sponsor budget mapping case","Participant enrollment case"]}),
feature("q0-q1-modifier-control","CRM09","Q0 Q1 modifier control","Execute q0 q1 modifier control using protocols, coverage analyses, budgets, informed consent, enrollment, orders, services, modifiers, claims, sponsor invoices, and payments.","Produce a governed q0 q1 modifier control decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Study / Participant Encounter","text","Study / Participant Encounter · Standard Case"],["caseReference","Q0 Q1 modifier control Reference","text","CRM09-2026-001"],["chargedAmount","Charged or Paid Amount","currency",672500],["supportedAmount","Evidence-Supported Amount","currency",564900],["domainDriver","Payer Responsibility","select","Routine cost",["Routine cost","Sponsor paid","Non-billable research"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"chargedAmount",subjects:["Study protocol registry case","Coverage analysis case","National coverage rule mapping case","Sponsor budget mapping case","Participant enrollment case"]}),
feature("diagnosis-code-validation","CRM10","Diagnosis code validation","Execute diagnosis code validation using protocols, coverage analyses, budgets, informed consent, enrollment, orders, services, modifiers, claims, sponsor invoices, and payments.","Produce a governed diagnosis code validation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Study / Participant Encounter","text","Study / Participant Encounter · Standard Case"],["caseReference","Diagnosis code validation Reference","text","CRM10-2026-001"],["chargedAmount","Charged or Paid Amount","currency",672500],["supportedAmount","Evidence-Supported Amount","currency",564900],["domainDriver","Payer Responsibility","select","Routine cost",["Routine cost","Sponsor paid","Non-billable research"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"chargedAmount",subjects:["Study protocol registry case","Coverage analysis case","National coverage rule mapping case","Sponsor budget mapping case","Participant enrollment case"]}),
feature("claim-prebill-review","CRM11","Claim prebill review","Execute claim prebill review using protocols, coverage analyses, budgets, informed consent, enrollment, orders, services, modifiers, claims, sponsor invoices, and payments.","Produce a governed claim prebill review decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Study / Participant Encounter","text","Study / Participant Encounter · Standard Case"],["caseReference","Claim prebill review Reference","text","CRM11-2026-001"],["chargedAmount","Charged or Paid Amount","currency",672500],["supportedAmount","Evidence-Supported Amount","currency",564900],["domainDriver","Payer Responsibility","select","Routine cost",["Routine cost","Sponsor paid","Non-billable research"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"chargedAmount",subjects:["Study protocol registry case","Coverage analysis case","National coverage rule mapping case","Sponsor budget mapping case","Participant enrollment case"]}),
feature("sponsor-invoice-reconciliation","CRM12","Sponsor invoice reconciliation","Execute sponsor invoice reconciliation using protocols, coverage analyses, budgets, informed consent, enrollment, orders, services, modifiers, claims, sponsor invoices, and payments.","Produce a governed sponsor invoice reconciliation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Study / Participant Encounter","text","Study / Participant Encounter · Standard Case"],["caseReference","Sponsor invoice reconciliation Reference","text","CRM12-2026-001"],["chargedAmount","Charged or Paid Amount","currency",672500],["supportedAmount","Evidence-Supported Amount","currency",564900],["domainDriver","Payer Responsibility","select","Routine cost",["Routine cost","Sponsor paid","Non-billable research"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"chargedAmount",subjects:["Study protocol registry case","Coverage analysis case","National coverage rule mapping case","Sponsor budget mapping case","Participant enrollment case"]}),
feature("double-bill-detection","CRM13","Double-bill detection","Execute double-bill detection using protocols, coverage analyses, budgets, informed consent, enrollment, orders, services, modifiers, claims, sponsor invoices, and payments.","Produce a governed double-bill detection decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Study / Participant Encounter","text","Study / Participant Encounter · Standard Case"],["caseReference","Double-bill detection Reference","text","CRM13-2026-001"],["chargedAmount","Charged or Paid Amount","currency",672500],["supportedAmount","Evidence-Supported Amount","currency",564900],["domainDriver","Payer Responsibility","select","Routine cost",["Routine cost","Sponsor paid","Non-billable research"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"chargedAmount",subjects:["Study protocol registry case","Coverage analysis case","National coverage rule mapping case","Sponsor budget mapping case","Participant enrollment case"]}),
feature("correction-refund-workflow","CRM14","Correction refund workflow","Execute correction refund workflow using protocols, coverage analyses, budgets, informed consent, enrollment, orders, services, modifiers, claims, sponsor invoices, and payments.","Produce a governed correction refund workflow decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Study / Participant Encounter","text","Study / Participant Encounter · Standard Case"],["caseReference","Correction refund workflow Reference","text","CRM14-2026-001"],["chargedAmount","Charged or Paid Amount","currency",672500],["supportedAmount","Evidence-Supported Amount","currency",564900],["domainDriver","Payer Responsibility","select","Routine cost",["Routine cost","Sponsor paid","Non-billable research"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"chargedAmount",subjects:["Study protocol registry case","Coverage analysis case","National coverage rule mapping case","Sponsor budget mapping case","Participant enrollment case"]}),
feature("study-billing-analytics","CRM15","Study billing analytics","Execute study billing analytics using protocols, coverage analyses, budgets, informed consent, enrollment, orders, services, modifiers, claims, sponsor invoices, and payments.","Produce a governed study billing analytics decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Study / Participant Encounter","text","Study / Participant Encounter · Standard Case"],["caseReference","Study billing analytics Reference","text","CRM15-2026-001"],["chargedAmount","Charged or Paid Amount","currency",672500],["supportedAmount","Evidence-Supported Amount","currency",564900],["domainDriver","Payer Responsibility","select","Routine cost",["Routine cost","Sponsor paid","Non-billable research"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"chargedAmount",subjects:["Study protocol registry case","Coverage analysis case","National coverage rule mapping case","Sponsor budget mapping case","Participant enrollment case"]})
]);
